package app.View;
import app.Model.Abstract.Shipping;
import app.Controller.ShippingModify;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Window.Type;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.border.TitledBorder;
import javax.swing.border.EtchedBorder;
import java.awt.Color;
import java.awt.event.MouseListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseAdapter;

/**
 *
 * @author Diep.Tran
 */
public class StudentFrame extends javax.swing.JFrame {
    DefaultTableModel tableModel;

    List<Shipping> studentList = new ArrayList<>();

    /**
     * Creates new form StudentFrame
     */
    public StudentFrame() {
        initComponents();

        tableModel = (DefaultTableModel) tblStudent.getModel();

        showStudent();
    }

    private void showStudent() {
        studentList = ShippingModify.findAll();

        tableModel.setRowCount(0);

        studentList.forEach((student) -> {
            tableModel.addRow(new Object[] { tableModel.getRowCount() + 1, student.getSenderName(), student.getSenderAddress(),student.getSendingTime(),
                    student.getReceiverName(), student.getReceiverAddress(), student.getReceivingTime(), 
                    student.getKm(), student.getKg(), student.getCost() });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtBirthday = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHospital = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        tblStudent.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                int selectedIndex = tblStudent.getSelectedRow();
                Shipping std = studentList.get(selectedIndex);
                txtFullname.setText(std.getFullname());
                cbGender.setSelectedIndex(std.getGender().equals("Male") ? 0 : 1);
                cbPosition.setSelectedIndex(std.getPosition().equals("Doctor") ? 0 : 1);
                txtBirthday.setText(std.getBirthday());
                txtHospital.setText(std.getHospital());
                txtPhoneNumber.setText(std.getPhoneNumber());
                txtWorking.setText(std.getWorking());
                txtSurgery.setText(std.getSurgery());
                txtNight.setText(std.getNight());
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Staff Management System");

        jPanel1.setBorder(new TitledBorder(null, "Input Staff's Detail Information", TitledBorder.LEADING,
                TitledBorder.TOP, null, null));

        jLabel1.setText("Full Name:");

        jLabel2.setText("Gender: ");

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel3.setText("Birthday:\r\n");

        jLabel4.setText("Hospital:");

        jLabel5.setText("Phone Number:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        cbPosition = new JComboBox<String>();
        cbPosition.setModel(new DefaultComboBoxModel(new String[] { "Doctor", "Nurse" }));

        jLabel2_1 = new JLabel();
        jLabel2_1.setText("Position:");

        lblNewLabel = new JLabel("Working Days");

        txtWorking = new JTextField();
        txtWorking.setColumns(10);

        JLabel lblNewLabel_1 = new JLabel("Number Of Surgery");

        txtSurgery = new JTextField();
        txtSurgery.setColumns(10);

        JLabel lblNewLabel_2 = new JLabel("Nights On Duty");

        txtNight = new JTextField();
        txtNight.setColumns(10);

        JButton btnEdit = new JButton("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        JButton btnSearchBySalary = new JButton("Search By Salary");
        btnSearchBySalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBySalaryActionPerformed(evt);
            }
        });

        cbFind = new JComboBox<String>();
        cbFind.setModel(new DefaultComboBoxModel(
                new String[] { "Full Name", "Gender", "Position", "Birthday", "Hospital", "Phone Number", "Salary" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout
                .createSequentialGroup().addGap(15)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
                        .addComponent(lblNewLabel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
                                GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, Alignment.LEADING).addComponent(jLabel2, Alignment.LEADING)
                        .addComponent(jLabel3, Alignment.LEADING)
                        .addComponent(jLabel5, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(jLabel4, Alignment.LEADING))
                .addGap(56).addGroup(
                        jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup().addComponent(btnFind).addGap(18)
                                        .addComponent(
                                                cbFind, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                .addComponent(txtHospital, 341, 521, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(cbGender, GroupLayout.PREFERRED_SIZE,
                                                                GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addGap(87)
                                                        .addComponent(jLabel2_1, GroupLayout.PREFERRED_SIZE, 63,
                                                                GroupLayout.PREFERRED_SIZE)
                                                        .addGap(44).addComponent(
                                                                cbPosition, GroupLayout.PREFERRED_SIZE, 96,
                                                                GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtFullname, 341, 521, Short.MAX_VALUE)
                                                .addComponent(txtBirthday, GroupLayout.DEFAULT_SIZE, 521,
                                                        Short.MAX_VALUE)
                                                .addComponent(txtPhoneNumber, GroupLayout.DEFAULT_SIZE, 521,
                                                        Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                                .addComponent(btnSave).addComponent(txtWorking,
                                                                        GroupLayout.PREFERRED_SIZE, 37,
                                                                        GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18)
                                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(btnEdit)
                                                                        .addPreferredGap(ComponentPlacement.UNRELATED)
                                                                        .addComponent(btnReset).addGap(16))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(lblNewLabel_1)
                                                                        .addPreferredGap(ComponentPlacement.UNRELATED)))
                                                        .addGroup(jPanel1Layout
                                                                .createParallelGroup(Alignment.LEADING)
                                                                .addComponent(
                                                                        txtSurgery, GroupLayout.PREFERRED_SIZE, 39,
                                                                        GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnDelete))
                                                        .addGap(18)
                                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(lblNewLabel_2,
                                                                                GroupLayout.PREFERRED_SIZE, 99,
                                                                                GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(28).addComponent(txtNight,
                                                                                GroupLayout.PREFERRED_SIZE, 32,
                                                                                GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(btnSearchBySalary))))
                                        .addGap(150)))));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout
                .createSequentialGroup().addGap(10)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel1).addComponent(
                        txtFullname, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel2)
                                .addComponent(cbGender, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                        GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                                .addComponent(cbPosition, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2_1, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel3).addComponent(
                        txtBirthday, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel4).addComponent(
                        txtHospital, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18)
                .addGroup(jPanel1Layout
                        .createParallelGroup(Alignment.BASELINE).addComponent(jLabel5).addComponent(txtPhoneNumber,
                                GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(lblNewLabel)
                        .addComponent(txtWorking, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSurgery, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNight, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNewLabel_2).addComponent(lblNewLabel_1))
                .addPreferredGap(ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(btnFind)
                        .addComponent(cbFind, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                .addGap(28)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(btnSave)
                        .addComponent(btnEdit).addComponent(btnDelete).addComponent(btnReset)
                        .addComponent(btnSearchBySalary))
                .addContainerGap()));
        jPanel1.setLayout(jPanel1Layout);

        tblStudent.setModel(new DefaultTableModel(new Object[][] {},
                new String[] { "ID", "Full Name", "Gender", "Position", "Birthday", "Hospital", "Phone Number",
                        "Working Days", "Surgery", "Night On Duty", "Salary" }));
        tblStudent.getColumnModel().getColumn(0).setPreferredWidth(48);
        tblStudent.getColumnModel().getColumn(6).setPreferredWidth(114);
        tblStudent.getColumnModel().getColumn(7).setPreferredWidth(97);
        tblStudent.getColumnModel().getColumn(9).setPreferredWidth(87);
        jScrollPane1.setViewportView(tblStudent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 825, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
                        .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 391, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 158, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        txtFullname.setText("");
        cbGender.setSelectedIndex(0);
        cbPosition.setSelectedIndex(0);
        txtBirthday.setText("");
        txtHospital.setText("");
        txtPhoneNumber.setText("");
        txtWorking.setText("");
        txtSurgery.setText("");
        txtNight.setText("");
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        String fullname = txtFullname.getText();
        String gender = cbGender.getSelectedItem().toString();
        String position = cbPosition.getSelectedItem().toString();
        String birthday = txtBirthday.getText();
        String hospital = txtHospital.getText();
        String phoneNumber = txtPhoneNumber.getText();
        String working = txtWorking.getText();
        String surgery = txtSurgery.getText();
        String night = txtNight.getText();
        int salary = 0;
        if (position.equals("Doctor")) {
            if (!working.equals(""))
                salary = Integer.parseInt(working) * 500000;
            if (!surgery.equals(""))
                salary += Integer.parseInt(surgery) * 2000000;
        }

        else {
            if (!working.equals(""))
                salary = Integer.parseInt(working) * 200000;
            if (!night.equals(""))
                salary += Integer.parseInt(night) * 500000;
        }

        Shipping std = new Shipping(fullname, gender, position, birthday, hospital, phoneNumber, working, surgery, night,
                String.valueOf(salary));

        ShippingModify.insert(std);

        showStudent();
    }

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int selectedIndex = tblStudent.getSelectedRow();
        if (selectedIndex >= 0) {
            Shipping std = studentList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this item?");
            System.out.println("option : " + option);

            if (option == 0) {
                ShippingModify.delete(std.getId());

                showStudent();
            }
        }
    }

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int selectedIndex = tblStudent.getSelectedRow();
        System.out.println(selectedIndex);

        if (selectedIndex >= 0) {
            Shipping stdstd = studentList.get(selectedIndex);
            String fullname = txtFullname.getText();
            String gender = cbGender.getSelectedItem().toString();
            String position = cbPosition.getSelectedItem().toString();
            String birthday = txtBirthday.getText();
            String hospital = txtHospital.getText();
            String phoneNumber = txtPhoneNumber.getText();
            String working = txtWorking.getText();
            String surgery = txtSurgery.getText();
            String night = txtNight.getText();
            int salary = 0;
            if (position.equals("Doctor"))
                salary = Integer.parseInt(working) * 500000 + Integer.parseInt(surgery) * 2000000;
            else
                salary = Integer.parseInt(working) * 200000 + Integer.parseInt(night) * 500000;

            Shipping std = new Shipping(stdstd.getId(), fullname, gender, position, birthday, hospital, phoneNumber,
                    working, surgery, night, String.valueOf(salary));

            ShippingModify.update(std);

            showStudent();
        }
    }

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Enter full name to search");
        if (input != null && input.length() > 0) {

            studentList = ShippingModify.findByInput(input, cbFind.getSelectedItem().toString());

            tableModel.setRowCount(0);

            studentList.forEach((student) -> {
                tableModel.addRow(new Object[] { tableModel.getRowCount() + 1, student.getFullname(),
                        student.getGender(), student.getPosition(), student.getBirthday(), student.getHospital(),
                        student.getPhoneNumber(), student.getWorking(), student.getSurgery(), student.getNight(),
                        student.getSalary() });
            });
        } else {
            showStudent();
        }
    }

    private void btnSearchBySalaryActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Enter salary to search ");
        if (input != null && input.length() > 0) {
            studentList = ShippingModify.searchBySalary(Integer.parseInt(input));

            tableModel.setRowCount(0);

            studentList.forEach((student) -> {
                tableModel.addRow(new Object[] { tableModel.getRowCount() + 1, student.getFullname(),
                        student.getGender(), student.getPosition(), student.getBirthday(), student.getHospital(),
                        student.getPhoneNumber(), student.getWorking(), student.getSurgery(), student.getNight(),
                        student.getSalary() });
            });
        } else {
            showStudent();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtHospital;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtPhoneNumber;
    private JComboBox<String> cbPosition;
    private JLabel jLabel2_1;
    private JLabel lblNewLabel;
    private JTextField txtWorking;
    private JTextField txtSurgery;
    private JTextField txtNight;
    private JComboBox<String> cbFind;
}
